GEOMETRY_PLUGIN_HYDRATE_COLOR=${GEOMETRY_PLUGIN_HYDRATE_COLOR:-blue}
GEOMETRY_PLUGIN_HYDRATE_SYMBOL=${GEOMETRY_PLUGIN_HYDRATE_SYMBOL:-💧}
GEOMETRY_PLUGIN_HYDRATE_FILE=${GEOMETRY_PLUGIN_HYDRATE_FILE:-${TMPDIR:-/tmp}/water}
GEOMETRY_PLUGIN_HYDRATE_INTERVAL=${GEOMETRY_PLUGIN_HYDRATE_INTERVAL:-20} # in minutes

geometry_prompt_hydrate_setup() {
  test -f $GEOMETRY_PLUGIN_HYDRATE_FILE || touch $GEOMETRY_PLUGIN_HYDRATE_FILE
}

geometry_prompt_hydrate_check() {
  test $(print $GEOMETRY_PLUGIN_HYDRATE_FILE(.Nmm+$GEOMETRY_PLUGIN_HYDRATE_INTERVAL))
}

geometry_prompt_hydrate_render() {
  echo $(prompt_geometry_colorize $GEOMETRY_PLUGIN_HYDRATE_COLOR $GEOMETRY_PLUGIN_HYDRATE_SYMBOL)
}

hydrate() {
  touch $GEOMETRY_PLUGIN_HYDRATE_FILE
}

geometry_plugin_register hydrate
